source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'Sample' do
	pod 'Texture/IGListKit', :path => '../..'
	pod 'Texture/PINRemoteImage', :path => '../..'
	pod 'ASDKFluentExtensions', '~> 0.3'
end
